language: java
script:
- "./gradlew build"
deploy:
  provider: gae
  keyfile: springboot22-09d2ded0aca3.json
  project: springboot22
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_cde3dcce509b_key -iv $encrypted_cde3dcce509b_iv
  -in springboot22-09d2ded0aca3.json.enc -out springboot22-09d2ded0aca3.json -d
