language: java
services: docker

script:
  - ./gradlew build
    docker build -t steinko/todobackend .
    docker push steinko/todobackend
  
before_install:
  - openssl aes-256-cbc -K $encrypted_cde3dcce509b_key -iv $encrypted_cde3dcce509b_iv -in springboot22-09d2ded0aca3.json.enc -out springboot22-09d2ded0aca3.json -d
  - ./gcloud-sdk-install.sh
  - source /home/travis/.bashrc
  - ./gcloud-sdk-configure.sh
  - gcloud components update kubectl
install: 
  -  kubectl apply -f pod.yaml
  -  kubecti apply -f service.yaml



