language: java
jdk:
  - openjdk14
services: docker
addons:
   sonarcloud:
     organization: "steinko-github"
     token:
       secure: $SONAR_TOKEN

script:
  - ./gradlew build
  - docker build -t steinko/todobackend .
  - docker login --username steinko --password RoxyMusic11
  - docker push steinko/todobackend
  - gradle jacocoTestReport
  - gradle sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$SONAR_PROJECT_KEY


