apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: todo
    tier: backend
    env: dev
spec:
  containers:
      - name: todo-backend-container
        image: docker.io/steinko/todobackend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP