apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  namespace: test
  labels:
    app: todo
    tier: data
spec:
  containers:
    - name: postgres-container  
      image: docker.io/postgres:latest
      ports:
        - containerPort: 5432
          name: http
          protocol: TCP
      envFrom:
        - configMapRef:
            name: postgres-config
      volumeMounts:
         - mountPath: /var/lib/postgresql/data
           name: postgres-volume
  volumes:
    - name: postgres-volume
      persistentVolumeClaim:
        claimName: postgres-volum-claim